version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
